### ISSUE TITLE
下载安装后一直闪退，求解决啊！我是小米系统8.5

### ISSUE THREAD

**Issue by chendddd1996** [NuclearVGA/EhViewer#10]
**简略描述 / Describe the bug**
大概说下是什么问题。

**如何重现 / To Reproduce**
重现的步骤：
1. 打开什么什么
2. 点击什么什么
3. 出现什么什么问题

**预期行为 / Expected behavior**
应该是什么样子的？

**截图 / Screenshots**
能截图的话就发截图，请注意风序良俗。

**设备型号与 Android 版本 / Device model and Android version**
 - 设备型号：【比如 Pixel 6 XXXL】
 - Android 版本：【比如 Android 12.1】
 - Device model: [e.g. Pixel 6 XXXL]
 - Android version: [e.g. Android 12.1]

**备注 / Additional context**
还有什么想说的？

**Comment by duzhaokun123** [comment]
清数据, 再不行卸了重装, 但很明显你的本地收藏没了

就没有日志吗

**Comment by duzhaokun123** [comment]
如果 root 了, 就把`/data/data/<应用包名>/databases/eh.db`复制出来, 那个就是本地收藏

**Comment by NuclearVGA** [comment]
@chendddd1996 发一下日志吧，在 内部存储/Andorid/data/com.hippo.ehviewer/crashs

**Comment by NuclearVGA** [comment]
我找到问题了，由于翻译源的变更，我引入了java.util.Base64来对下载的字典文件进行解码，这个库在较低版本的安卓不存在。
安卓SDK下载贼慢，所以我只装了API29的AVD，结果，没发现这个Bug(›´ω`‹ )

**Comment by chendddd1996** [comment]
修复了吗？

**Comment by NuclearVGA** [comment]
修复了，但是笔记本没电了，我明天上午还有课，等我中午才能更新

**Comment by chendddd1996** [comment]
太感谢了，谢谢了
