### ISSUE TITLE
一加8 pro 无法安装apk 提示未安装应用

### ISSUE THREAD

**Issue by philipdeng** [NuclearVGA/EhViewer#11]
**简略描述 / Describe the bug**
大概说下是什么问题。

已安装原1.7.16和1.7.14 无法安装1.7.16.3

**如何重现 / To Reproduce**
重现的步骤：
1. 打开什么什么
2. 点击什么什么
3. 出现什么什么问题

使用一加8pro 手机安装apk 两个安装包都不行

**预期行为 / Expected behavior**
应该是什么样子的？

成功安装

**截图 / Screenshots**
能截图的话就发截图，请注意风序良俗。
![Screenshot_20201205-001908](https://user-images.githubusercontent.com/22946991/101188191-55f14d80-3690-11eb-8de0-14197f1a41b8.jpg)

**设备型号与 Android 版本 / Device model and Android version**
 - 设备型号：【比如 Pixel 6 XXXL】
 - Android 版本：【比如 Android 12.1】
 - Device model: [e.g. Pixel 6 XXXL]
 - Android version: [e.g. Android 12.1]

设备 oneplus 8 pro
安卓版本 11
系统版本 氢OS 11.0.2.2IN11

**备注 / Additional context**
还有什么想说的？

感谢大佬

**Comment by duzhaokun123** [comment]
签名密钥不一样, 没法覆盖, 卸了重装, 记得备份本地收藏
