### ISSUE TITLE
让APP回归原始状态的看法

### ISSUE THREAD

**Issue by Mapaler** [NuclearVGA/EhViewer#5]
1. 有风险的信息抓取删掉
![Screenshot_20201203-065147](https://user-images.githubusercontent.com/6565860/100941226-43fa9800-3534-11eb-8dbd-8535354f91d4.png)
2. 包名改回`com.hippo.ehviewer`保持向前兼容，哪怕证书不同有核心破解就可以直接覆盖安装，免得每次换个人开发就得重新配置一遍。

**Comment by NuclearVGA** [comment]
已经实现了此建议
